absensi_apps/urls.py
from django.urls import path
from . import views

app_name = 'absensi'

urlpatterns = [
    # path('')
    path('absen/', views.Scan, name='absen'),
    # path('keluar/', views.keluar, name='keluar'),
    # path('kendala/', include('covid19_apps.urls', namespace='kendala')),
    path('', views.index, name='list'),
    # path('logout/', views.singout, name='logout'),
]

webapps/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
# from decorator_include import decorator_include
from . import views
from absensi_apps import views as apps_views

urlpatterns = [
    # path('')
    path('admin/', admin.site.urls),
    path('daftar/', views.register, name='register'),
    path('login/', views.signin, name='login'),
    path('kendala/', include('covid19_apps.urls', namespace='kendala')),
    path('absensi/', include('absensi_apps.urls', namespace='absensi')),
    path('stockopname/', include('stockopname.urls', namespace='stockopname')),
    path('fontawesome/', views.fontawesome, name='fontawesome'),
    path('themify/', views.themify, name='themify'),
    # path('stockopname/', decorator_include(login_required, 'stockopname.urls', namespace='stockopname')),
    path('', apps_views.index, name='home'),
    path('logout/', views.singout, name='logout'),
]

absensi_apps/models.py
from django.db import models
from django.contrib.auth.models import User
# import datetime
# Create your models here.

PILIHAN = (
    (1,'JAM MASUK'),
    (2,'JAM PULANG'),
)

class Nik(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    nik = models.CharField(max_length=9)

    def __str__(self):
        return '{}'.format(self.nik)
    

class Scan_Absen(models.Model):
    nik = models.ForeignKey(Nik, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    pilihan = models.IntegerField(choices=PILIHAN)
    jam = models.DateTimeField(auto_now_add=True)

    

absensi_apps/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
from .models import Scan_Absen, Nik
from .form import ScanForm
import datetime
# Create your views here.

@login_required(login_url='login')
def index(request):
    
    cuser = request.user
    admin = User.objects.filter(username=cuser,is_superuser=True)
    if admin:
        datas = Scan_Absen.objects.all().order_by('user__first_name')

        return render(request, 'absensi_apps/index.html', {'datas':datas})
    else:
        datas = Scan_Absen.objects.select_related('user').filter(user_id=cuser)
        nama = User.objects.filter(username=cuser)

        args = {
            'cuser':cuser,
            'datas':datas,
            'nama':nama
        
        }
        
        return render(request, 'absensi_apps/index.html', args)

@login_required(login_url='login')
def Scan(request):

    cuser = request.user
    # niks = Nik.objects.select_related('user').filter(user__username=cuser).first()
    nama = User.objects.filter(username=cuser)
    nik = Nik.objects.get(user=request.user) 

    if request.method == 'POST':
        
        form = ScanForm(request.POST)
        # print(form)
        
        if form.is_valid:
            post = form.save(commit=False)
            post.user = request.user
            post.nik = nik
            post.save()

            return HttpResponseRedirect(reverse('absensi:list'))
        
    else:
        form = ScanForm()
        cuser = request.user
    return render(request, 'absensi_apps/absen.html', {'form':form, 'cuser':cuser, 'nik':nik, 'nama':nama})

absensi_apps/templates/absensi_apps/absen.html
{% extends 'base.html' %}

{% block title %}
Absen Jam Masuk dan Jam Pulang
{% endblock title %}

{% block content %}


<div class="col-lg-6">
    <div class="card">
        <div class="card-header">
            <strong>Absensi</strong> {% for namas in nama %}{{namas.get_full_name}}{% endfor %} - {{nik}}
        </div>
        <div class="card-body card-block">
            <form method="post" class="form-horizontal">
                {% csrf_token %}
                
                 <div class="row form-group">
                    <div class="col col-md-3"><label for="selectLg" class=" form-control-label">Jam Absen</label></div>
                    <div class="col-12 col-md-9">
                    {{form.pilihan}}
                    </div>
                </div>
                
                <div class="card-footer">
                <button type="submit" class="btn btn-primary btn-sm">
                    <i class="fa fa-dot-circle-o"></i> Submit
                </button>
            </div>
            </form>
            
        </div>
    </div>
</div>

{% endblock content %}

absensi_apps/templates/absensi_apps/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Selamat Datang - {{cuser}}
{% endblock title %}

{% block head %}
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'font-awesome/css/font-awesome.css' %}" rel="stylesheet">

    <link href="{% static 'css/plugins/dataTables/datatables.min.css' %}" rel="stylesheet">

    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
{% endblock head %}

    {% block content %}
    {% if messages %}
    {% for message in messages %}
        <div class="sufee-alert alert with-close alert-success alert-dismissible fade show">
            <span class="badge badge-pill badge-success">Success</span>
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endfor %}
{% endif %}
    <div class="row wrapper border-bottom white-bg page-heading">
                <div class="col-lg-10">
                    <h2>Daftar Absensi</h2>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="{% url 'home' %}">Home</a>
                        </li>
                        <li class="breadcrumb-item">
                            <a>Absen</a>
                        </li>
                        <li class="breadcrumb-item active">
                            <strong>Daftar Absen</strong>
                        </li>
                    </ol>
                </div>
                <div class="col-lg-2">

                </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-lg-12">
                <div class="ibox ">
                    <div class="ibox-title">
                        <h5>Daftar Absensi {{cuser}} - 
                                {% for namas in nama %}
                                    {{namas.get_full_name}}
                                {% endfor %}
                        </h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#" class="dropdown-item">Config option 1</a>
                                </li>
                                <li><a href="#" class="dropdown-item">Config option 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">

                        <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover dataTables-example" >
                    <thead>
                    <tr>
                        <th class="serial">No</th>
                        <th>Kode User</th>
                        <th>NPK</th>
                        <th>Nama</th>
                        <th>Jenis Absen</th>
                        <th>Jam Masuk/</br>Keluar</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for data in datas  %}
                    <tr class="gradeX">
                        <td class="serial">{{forloop.counter}}</td>
                                            
                        <td><span class="name">{{data.user}}</span></td>
                        <td><span class="serial">{{data.nik}}</span></td>
                        <td>  <span class="name">{{data.user.get_full_name}}</span> </td>
                        <td>
                            {{data.get_pilihan_display}}
                        </td>
                        <td>
                            {{data.jam}}
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                    <tfoot>
                    <tr>
                       <th class="serial">No</th>
                        <th>Kode User</th>
                        <th>NPK</th>
                        <th>Nama</th>
                        <th>Jenis Absen</th>
                        <th>Jam Masuk/</br>Keluar</th>
                    </tr>
                    </tfoot>
                    </table>
                        </div>

                    </div>
                </div>
            </div>
            </div>
    </div>
   
    {% endblock content %}

    {% block extra_js %}

    <!-- Mainly scripts -->
    <script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/metisMenu/jquery.metisMenu.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>

    <script type="text/javascript" src="{% static 'js/plugins/dataTables/datatables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/dataTables/dataTables.bootstrap4.min.js' %}"></script>

    <!-- Custom and plugin javascript -->
    <script src="{% static 'js/inspinia.js' %}"></script>
    <script src="{% static 'js/plugins/pace/pace.min.js' %}"></script>

    <!-- Page-Level Scripts -->
    <script>
        $(document).ready(function(){
            $('.dataTables-example').DataTable({
                pageLength: 25,
                responsive: true,
                dom: '<"html5buttons"B>lTfgitp',
                buttons: [
                    { extend: 'copy'},
                    {extend: 'csv'},
                    {extend: 'excel', title: 'ExampleFile'},
                    {extend: 'pdf', title: 'ExampleFile'},

                    {extend: 'print',
                     customize: function (win){
                            $(win.document.body).addClass('white-bg');
                            $(win.document.body).css('font-size', '10px');

                            $(win.document.body).find('table')
                                    .addClass('compact')
                                    .css('font-size', 'inherit');
                    }
                    }
                ]

            });

        });

    </script>

    {% endblock extra_js %}
        
     