stockopname/urls.py
from django.urls import path, include
from .views import AppStok


app_name = 'stockopname'
urlpatterns = [
    path('', AppStok.index, name='list'),
    # path('ajax_calls/search/', AppStok.autocompleteModel, name='search'),
    path('permintaan/<int:pk>', AppStok.PermintaanProduk, name='permintaan'),
    path('permintaan/list/', AppStok.permintaan_list, name='permintaan_list'),
    path('input/', AppStok.InputProduk, name='input'),
    path('sisa/', AppStok.sisa_stok, name='sisa'),
]

webapps/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
# from decorator_include import decorator_include
from . import views
from absensi_apps import views as apps_views

urlpatterns = [
    # path('')
    path('admin/', admin.site.urls),
    path('daftar/', views.register, name='register'),
    path('login/', views.signin, name='login'),
    path('kendala/', include('covid19_apps.urls', namespace='kendala')),
    path('absensi/', include('absensi_apps.urls', namespace='absensi')),
    path('stockopname/', include('stockopname.urls', namespace='stockopname')),
    path('fontawesome/', views.fontawesome, name='fontawesome'),
    path('themify/', views.themify, name='themify'),
    # path('stockopname/', decorator_include(login_required, 'stockopname.urls', namespace='stockopname')),
    path('', apps_views.index, name='home'),
    path('logout/', views.singout, name='logout'),
]

stockopname/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

PILIHAN = (
    (1,'Tersedia'),
    (2,'Kosong'),
)

KATEGORI = (
    (1,'CETAKAN'),
    (2,'ATK'),
    (3,'CONSUMABLE'),
)

SATUAN = (
    (1,'RIM'),
    (2,'BLK'),
    (3,'KBLK'),
    (4,'BKS'),
    (5,'BH'),
    (6,'KTK'),
    (7,'PAK'),
    (8,'PS'),

)

class Produk(models.Model):
    kategori = models.IntegerField(choices=KATEGORI)
    nama = models.CharField(max_length=50)
    jumlah = models.IntegerField()
    per_unit = models.IntegerField()
    satuan = models.IntegerField(choices=SATUAN)
    harga = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    def status(self):
        if self.jumlah <= 0:
            status = 'Y'
        else:
            status = 'N'
        return '{}'.format(status)
    
    def total_unit(self):

        return '{}'.format(self.jumlah*self.per_unit)

    def total(self):
        
        return '{}'.format(self.jumlah*self.harga)
    
    def __str__(self):
        return '{}'.format(self.nama)
    

class Permintaan(models.Model):
    produk = models.ForeignKey(Produk, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    jumlah = models.IntegerField()
    # sisa = models.IntegerField(default=0)
    tgl = models.DateTimeField(auto_now_add=True)

    def sisa(self):

        self.sisa = 0

        if self.sisa:

            self.sisa = Produk.total_unit - self.jumlah
        else:
            return '{}'.format(Produk.jumlah)
    
    def HargaSisa(self):
        unit = Produk.harga/Produk.per_unit
        self.HargaSisa = self.sisa * unit
        return '{}'.format(self.HargaSisa)

stockopname/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http.response import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.forms import inlineformset_factory
from django.urls import reverse
from django.contrib.auth.models import User
from .form import PermintaanForm, ProdukForm
from .models import *
from django.views import View
# Create your views here.

# @login_required(login_url='login')
# @method_decorator(login_required, name='login')
class AppStok(View):
    # login_url = 'login/'
    # redirect_field_name = 'login/'
    @login_required(login_url='login')
    def index(request):

        # datas = SisaStok.objects.all()
        datas = Produk.objects.all()

        return render(request,'apps/index.html', {'datas':datas, 'cuser':request.user})
    
    def permintaan_list(request):

        cuser = request.user
        datas = Permintaan.objects.select_related('produk').all()
        return render(request, 'apps/permintaan_list.html', {'datas':datas, 'cuser':cuser})

    @login_required(login_url='login')
    def InputProduk(request):
        if request.method == 'POST':
            form = ProdukForm(request.POST)
            if form.is_valid:
                post = form.save(commit=False)
                post.user = request.user
                post.save()

                return HttpResponseRedirect(reverse('stockopname:list'))
        else:
            form = ProdukForm()
        return render(request, 'apps/input.html',{'form':form})
    
    @login_required(login_url='login')
    def PermintaanProduk(request, pk):
        
        cuser = request.user
        data = get_object_or_404(Produk, pk=pk)
        if request.method == 'POST':
            
            form = PermintaanForm(request.POST)
            # print(form)
            
            if form.is_valid:
                post = form.save(commit=False)
                post.user = request.user
                post.produk_id = data.pk
                post.save()

                return HttpResponseRedirect(reverse('stockopname:permintaan_list'))
            
        else:
            form = PermintaanForm()
            cuser = request.user
        return render(request, 'apps/permintaan.html', {'form':form, 'cuser':cuser, 'data':data.nama})
    
    @login_required(login_url='login')
    def sisa_stok(request):

        datas = Permintaan.objects.select_related('produk').all()
        return render(request, 'apps/sisa.html', {'datas':datas})

    def autocompleteModel(request):
        if request.is_ajax():
            q = request.GET.get('term', '').capitalize()
            search_qs = Mas.objects.filter(name__startswith=q)
            results = []
            print(q)
            for r in search_qs:
                results.append(r.FIELD)
            data = json.dumps(results)
        else:
            data = 'fail'
        mimetype = 'application/json'
        return HttpResponse(data, mimetype)

stockopname/templates/apps/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}List Stockopname{% endblock title %}

{% block style %}
{% endblock style %}

{% block breadcrumbs %}
<div class="breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-12">
                <div class="page-header float-left">
                    <div class="page-title">
                        <ol class="breadcrumb text-right">
                            <li><a href="{% url 'home' %}">Dashboard</a></li>
                            <li class="active">List Stockopname</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock breadcrumbs %}

{% block content %}
<div class="content">
    <!-- Animated -->
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <div class="row m-0">
                        <div class="col">
                            <strong class="card-title">List Stockopname</strong>
                        </div>
                        <div class="col" align="right">
                            <a href="{% url 'stockopname:input' %}" class="btn btn-primary btn-sm"
                                role="button">Tambah</a>
                        </div>
                    </div>
                </div>
                <div class="card-body--">
                    <div class="table-stats order-table ov-h">
                        <table class="table ">
                            <thead>
                                <tr>
                                    <th class="serial">#</th>
                                    <th class="avatar">Gambar</th>
                                    <th>Nama</th>
                                    <th>Keterangan</th>
                                    <th>Stok</th>
                                    <th>Status</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for data in data_obat %}
                                <tr>
                                    <td class="serial">{{ forloop.counter }}</td>
                                    <td class="avatar">
                                        <div class="round-img">
                                            <a href="#"><img class="rounded-circle"
                                                    src="{% if data.gambar %}{{ data.gambar.url }}{% else %}#{% endif %}"
                                                    alt=""></a>
                                        </div>
                                    </td>
                                    <td><a href="{% url 'jadwal:detail_obat' pk=data.pk %}">{{ data.nama }}</a></td>
                                    <td>{{ data.keterangan|linebreaksbr }}</td>
                                    <td>{{ data.jumlah }}</td>
                                    {% if data.jumlah >= 0 and data.jumlah <= 4 %}
                                    <td>
                                        <span class="badge badge-pending">Beli obat</span>
                                    </td>
                                    {% elif data.jumlah > 4 and data.jumlah <= 8 %}
                                    <td>
                                        <span class="badge badge-warning">Siap-siap</span>
                                    </td>
                                    {% else %}
                                    <td>
                                        <span class="badge badge-complete">Aman</span>
                                    </td>
                                    {% endif %}
                                    <td align="right">
                                        <a href="{% url 'jadwal:edit_obat' pk=data.pk %}"><i class="fa fa-pencil"></i>
                                            edit</a> |
                                        <a href="#" data-toggle="modal" data-target="#staticModal{{ data.pk }}"><i
                                                class="fa fa-trash-o"></i>
                                            hapus</a>
                                    </td>
                                </tr>
                                <div class="modal fade" id="staticModal{{ data.pk }}" tabindex="-1" role="dialog"
                                    aria-labelledby="staticModalLabel" aria-hidden="true">
                                    <div class="modal-dialog modal-sm" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <div class="alert alert-danger" role="alert">
                                                    <h5 class="modal-title" id="staticModalLabel">Peringatan</h5>
                                                </div>
                                                <button type="button" class="close" data-dismiss="modal"
                                                    aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <p>
                                                    Apakah anda ingin menghapus obat {{ data.nama }}?
                                                </p>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary btn-sm"
                                                    data-dismiss="modal">Batal</button>
                                                <a class="btn btn-danger btn-sm" role="button"
                                                    href="{% url 'jadwal:hapus_obat' pk=data.pk %}">Iya</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block script %}
{% endblock script %}

stockopname/templates/apps/input.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Form Input Stockopname Kacab Langsa
{% endblock title %}

{% block head %}
<link rel="icon" href="{% static 'images\favicon.ico' %}" type="image/x-icon">
<!-- Google font-->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,800" rel="stylesheet">
<!-- Required Fremwork -->
<link rel="stylesheet" type="text/css" href="{% static 'css\bootstrap.min.css' %}">
<!-- themify-icons line icon -->
<link rel="stylesheet" type="text/css" href="{% static 'icon\themify-icons\themify-icons.css' %}">
<!-- ico font -->
<link rel="stylesheet" type="text/css" href="{% static 'icon\icofont\css\icofont.css' %}">
<!-- feather Awesome -->
<link rel="stylesheet" type="text/css" href="{% static 'icon\feather\css\feather.css' %}">
<!-- Style.css -->
<link rel="stylesheet" type="text/css" href="{% static 'css\style.css' %}">


<link rel="stylesheet" type="text/css" href="{% static 'css\jquery.mCustomScrollbar.css' %}">
{% endblock head %}

{% block content %}
<div class="pcoded-content">
<div class="pcoded-inner-content">
<!-- Main-body start -->
<div class="main-body">
<div class="page-wrapper">
<!-- Page-header start -->
<div class="pcoded-content">
<div class="pcoded-inner-content">
<!-- Main-body start -->
<div class="main-body">
<div class="page-wrapper">
<!-- Page-header start -->
<div class="page-header">
    <div class="row align-items-end">
        <div class="col-lg-8">
            <div class="page-header-title">
                <div class="d-inline">
                    <h4>Basic Form Inputs</h4>
                    <span>Lorem ipsum dolor sit <code>amet</code>, consectetur adipisicing elit</span>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="page-header-breadcrumb">
                <ul class="breadcrumb-title">
                    <li class="breadcrumb-item">
                        <a href="index-1.htm"> <i class="feather icon-home"></i> </a>
                    </li>
                    <li class="breadcrumb-item"><a href="#!">Form Components</a>
                    </li>
                    <li class="breadcrumb-item"><a href="#!">Form Components</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- Page-header end -->
    <div class="page-body">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h5>Form Permintaan</h5>
                        <span>Add class of <code>.form-control</code> with <code>&lt;input&gt;</code> tag</span>
                        <div class="card-header-right"><i class="icofont icofont-spinner-alt-5"></i></div>
                    </div>
                    
                    <div class="card-block">
                        <h4 class="sub-title">Input Stockopname</h4>
                        <form method="POST">
                        {% csrf_token %}
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">Kategori</label>
                                <div class="col-sm-10">
                                    {{form.kategori}}
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">Nama</label>
                                <div class="col-sm-10">
                                    {{form.nama}}
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">Jumlah</label>
                                <div class="col-sm-10">
                                    {{form.jumlah}}
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">Jumlah Per Unit</label>
                                <div class="col-sm-10">
                                    {{form.per_unit}}
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">Satuan</label>
                                <div class="col-sm-10">
                                    {{form.satuan}}
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">Harga</label>
                                <div class="col-sm-10">
                                    {{form.harga}}
                                </div>
                            </div>
                            
                            <div class="row">
                                <label class="col-sm-2"></label>
                                <div class="col-sm-10">
                                    <button type="submit" class="btn btn-primary m-b-0">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block extra_js %}

<!-- Required Jquery -->
    <script type="text/javascript" src="{% static 'bower_components\jquery\js\jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bower_components\jquery-ui\js\jquery-ui.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bower_components\popper.js\js\popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bower_components\bootstrap\js\bootstrap.min.js' %}"></script>
    <!-- jquery slimscroll js -->
    <script type="text/javascript" src="{% static 'bower_components\jquery-slimscroll\js\jquery.slimscroll.js' %}"></script>
    <!-- modernizr js -->
    <script type="text/javascript" src="{% static 'bower_components\modernizr\js\modernizr.js' %}"></script>
    <script type="text/javascript" src="{% static 'bower_components\modernizr\js\css-scrollbars.js' %}"></script>

    <!-- Validation js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"></script>
    <script type="text/javascript" src="{% static 'pages\form-validation\validate.js' %}"></script>
    <!-- i18next.min.js -->
    <script type="text/javascript" src="{% static 'bower_components\i18next\js\i18next.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bower_components\i18next-xhr-backend\js\i18nextXHRBackend.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bower_components\i18next-browser-languagedetector\js\i18nextBrowserLanguageDetector.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bower_components\jquery-i18next\js\jquery-i18next.min.js' %}"></script>
    <!-- Custom js -->
    <script type="text/javascript" src="{% static 'pages\form-validation\form-validation.js' %}"></script>

    <script src="{% static 'js\pcoded.min.js' %}"></script>
    <script src="{% static 'js\vartical-layout.min.js' %}"></script>
    <script src="{% static 'js\jquery.mCustomScrollbar.concat.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js\script.js' %}"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>

{% endblock extra_js %}

stockopname/templates/apps/permintaan.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Form Permintaan Barang
{% endblock title %}

{% block head %}
 <!-- Favicon icon -->
    <link rel="icon" href="{% static 'images\favicon.ico' %}" type="image/x-icon">
    <!-- Google font--><link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,800" rel="stylesheet">
    <!-- Required Fremwork -->
    <link rel="stylesheet" type="text/css" href="{% static 'bower_components\bootstrap\css\bootstrap.min.css' %}">
    <!-- themify-icons line icon -->
    <link rel="stylesheet" type="text/css" href="{% static 'icon\themify-icons\themify-icons.css' %}">
    <!-- ico font -->
    <link rel="stylesheet" type="text/css" href="{% static 'icon\icofont\css\icofont.css' %}">
    <!-- feather Awesome -->
    <link rel="stylesheet" type="text/css" href="{% static 'icon\feather\css\feather.css' %}">
    <!-- Style.css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css\style.css' %}">


    <link rel="stylesheet" type="text/css" href="{% static 'css\jquery.mCustomScrollbar.css' %}">
{% endblock head %}

{% block content %}
<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <!-- Main-body start -->
        <div class="main-body">
            <div class="page-wrapper">
                <!-- Page-header start -->
                <div class="page-header">
                    <div class="row align-items-end">
                        <div class="col-lg-8">
                            <div class="page-header-title">
                                <div class="d-inline">
                                    <h4>Basic Form Inputs</h4>
                                    <span>Lorem ipsum dolor sit <code>amet</code>, consectetur adipisicing elit</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="page-header-breadcrumb">
                                <ul class="breadcrumb-title">
                                    <li class="breadcrumb-item">
                                        <a href="index-1.htm"> <i class="feather icon-home"></i> </a>
                                    </li>
                                    <li class="breadcrumb-item"><a href="#!">Form Components</a>
                                    </li>
                                    <li class="breadcrumb-item"><a href="#!">Form Components</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- page header end -->

                <!-- page body start -->
                <div class="page-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <!-- Basic Form Inputs card start -->
                            <div class="card">
                                <div class="card-header">
                                    <h5>Basic Form Inputs</h5>
                                    <span>Add class of <code>.form-control</code> with <code>&lt;input&gt;</code> tag</span>


                                    <div class="card-header-right">
                                        <i class="icofont icofont-spinner-alt-5"></i>
                                    </div>

                                </div>
                                <div class="card-block">
                                    <h4 class="sub-title">Basic Inputs</h4>
                                    <form method="POST">
                                        {% csrf_token %}
                                        <div class="form-group row">
                                            <label class="col-sm-2 col-form-label">Produk</label>
                                            <div class="col-sm-10">
                                                <p class="form-control-static">{{data}}</p>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-2 col-form-label">Jumlah</label>
                                            <div class="col-sm-10">
                                                {{form.jumlah}}
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <button type="submit">Save</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- page body end -->
            </div>
        </div>
    </div>
</div>            
{% endblock content %}