stockopname/urls.py
from django.urls import path, include
from .views import AppStok


app_name = 'stockopname'
urlpatterns = [
    path('', AppStok.index, name='list'),
    # path('ajax_calls/search/', AppStok.autocompleteModel, name='search'),
    path('permintaan/<int:pk>', AppStok.PermintaanProduk, name='permintaan'),
    path('permintaan/list/', AppStok.permintaan_list, name='permintaan_list'),
    path('input/', AppStok.InputProduk, name='input'),
    path('sisa/', AppStok.sisa_stok, name='sisa'),
]

webapps/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
# from decorator_include import decorator_include
from . import views
from absensi_apps import views as apps_views

urlpatterns = [
    # path('')
    path('admin/', admin.site.urls),
    path('daftar/', views.register, name='register'),
    path('login/', views.signin, name='login'),
    path('kendala/', include('covid19_apps.urls', namespace='kendala')),
    path('absensi/', include('absensi_apps.urls', namespace='absensi')),
    path('stockopname/', include('stockopname.urls', namespace='stockopname')),
    path('fontawesome/', views.fontawesome, name='fontawesome'),
    path('themify/', views.themify, name='themify'),
    # path('stockopname/', decorator_include(login_required, 'stockopname.urls', namespace='stockopname')),
    path('', apps_views.index, name='home'),
    path('logout/', views.singout, name='logout'),
]

templates/base.html
{% load static %}

<!doctype html>
<html class="no-js" lang="en">

<head>
    <title>{% block title %}{% endblock title %}</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="apple-touch-icon" href="{% static 'images/druids.png' %}">
    <link rel="shortcut icon" href="{% static 'images/druids.png' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/normalize.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-capicons.css' %}">
    <link rel="stylesheet" href="{% static 'css/ie7.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/pe-icon-7-stroke.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/flag-icon.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/cs-skin-elastic.css' %}">

    {% block style %}
    {% endblock style %}

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body class="d-flex flex-column">
    <!-- Left Panel -->
    {% if request.user.is_authenticated %}
    {% include 'navbar.html' %}
    {% endif %}
    <!-- /#left-panel -->

    <!-- Right Panel -->
    {% if request.user.is_authenticated %}
    <div id="right-panel" class="right-panel">
        <!-- Header-->
        {% include 'rightpanel.html' %}
        {% endif %}
        <!-- /#header -->

        {% block breadcrumbs %}
        {% endblock breadcrumbs %}

        <button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>

        {% block content %}
        {% endblock content %}

        <div class="clearfix"></div>

        <!-- Footer -->
        {% include 'footer.html' %}
        <!-- /.site-footer -->
    </div>
    <!-- /#right-panel -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.matchHeight.min.js' %}"></script>

    {% block script %}
    {% endblock script %}

    <script>
        //Get the button
        var mybutton = document.getElementById("myBtn");

        // When the user scrolls down 20px from the top of the document, show the button
        window.onscroll = function () {
            scrollFunction()
        };

        function scrollFunction() {
            if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
                mybutton.style.display = "block";
            } else {
                mybutton.style.display = "none";
            }
        }

        // When the user clicks on the button, scroll to the top of the document
        function topFunction() {
            document.body.scrollTop = 0;
            document.documentElement.scrollTop = 0;
        }

    </script>

    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/footer.html
<div id="footer" class="footer">
    <footer class="site-footer">
        <div class="footer-inner bg-white">
            <div class="row">
                <div class="col-sm-6">
                    Copyright &copy; 2020 DRuiDS
                </div>
                <div class="col-sm-6 text-right">
                    Designed by <a href="https://colorlib.com">Colorlib</a>
                </div>
            </div>
        </div>
    </footer>
</div>

templates/login.html
{% extends "base.html" %}

{% block title %}Log-in{% endblock %}

{% block content %}
    <h1>Log-in</h1>
    <p>Please, use the following form to log-in:</p>
    <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Log in"></p>
{% endblock %}

templates/login1.html
{% load static %}
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>INSPINIA | Login</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'font-awesome/css/font-awesome.css' %}" rel="stylesheet">

    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>

<body class="gray-bg">

    <div class="middle-box text-center loginscreen animated fadeInDown">
        <div>
            <div>

                <h1 class="logo-name">IN+</h1>

            </div>
            <h3>Welcome to IN+</h3>
            <p>Perfectly designed and precisely prepared admin theme with over 50 pages with extra new web app views.
                <!--Continually expanded and constantly improved Inspinia Admin Them (IN+)-->
            </p>
            <p>Login in. To see it in action.</p>
            {% if messages %}
                    {% for message in messages  %}
                        <div class="sufee-alert alert with-close alert-danger alert-dismissible fade show">
                            <span class="badge badge-pill badge-danger">Alert!</span>
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endfor %}
                {% endif %}
            <form class="m-t" role="form" method="POST">
            {% csrf_token %}
                <div class="form-group">
                    {{form.username}}
                </div>
                <div class="form-group">
                    {{form.password}}
                </div>
                <button type="submit" class="btn btn-primary block full-width m-b">Login</button>

                <a href="#"><small>Forgot password?</small></a>
                <p class="text-muted text-center"><small>Do not have an account?</small></p>
                <a class="btn btn-sm btn-white btn-block" href="{% url 'register' %}">Create an account</a>
            </form>
            <p class="m-t"> <small>Inspinia we app framework base on Bootstrap 3 &copy; 2014</small> </p>
        </div>
    </div>

    <!-- Mainly scripts -->
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>

</body>

</html>

templates/navbar.html
{% if request.user.is_authenticated %}
<aside id="left-panel" class="left-panel">
    <nav class="navbar navbar-expand-sm navbar-default">
        <div id="main-menu" class="main-menu collapse navbar-collapse">
            <ul class="nav navbar-nav">
                {% with url_name=request.resolver_match.url_name %}
                <li class="{% if url_name == 'home' %}active{% endif %}">
                    <a href="{% url "home" %}"><i class="menu-icon fa fa-laptop"></i>Dashboard </a>
                </li>

                <li class="menu-title">Master Data</li><!-- /.menu-title -->
                <li
                    class="{% if url_name == 'list' or url_name == 'input' %}active{% endif %}">
                    <a href="{% url "stockopname:list" %}"><i class="menu-icon fa fa-medkit"></i>Data Produk</a>
                </li>
                <li class="menu-title">Permintaan Produk</li><!-- /.menu-title -->
                <li
                    class="menu-item-has-children dropdown {% if url_name == 'permintaan_list' or url_name == 'permintaan' %}active{% endif %}">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false"> <i class="menu-icon fa fa-calendar"></i>Permintaan Produk</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li>
                            <a href="{% url 'stockopname:permintaan_list' %}"><i class="menu-icon fa fa-th-list"></i>List Permintaan</a>
                        </li>
                        <li>
                            <a href="{% url 'stockopname:permintaan' %}"><i class="menu-icon icon-082"></i>Permintaan</a>
                        </li>
                        
                    </ul>
                </li>

                <li class="menu-title">Icons</li>

                <li
                    class="menu-item-has-children dropdown {% if url_name == 'fontawesome' or url_name == 'themify' %}active{% endif %}">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false"> <i class="menu-icon fa fa-tasks"></i>Icons</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="menu-icon fa fa-fort-awesome"></i><a href="{% url "fontawesome" %}">Font
                                Awesome</a></li>
                        <li><i class="menu-icon ti-themify-logo"></i><a href="{% url "themify" %}">Themefy Icons</a>
                        </li>
                    </ul>
                </li>
                <!-- <li>
                    <a href="widgets.html"> <i class="menu-icon ti-email"></i>Widgets </a>
                </li>
                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false"> <i class="menu-icon fa fa-bar-chart"></i>Charts</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="menu-icon fa fa-line-chart"></i><a href="charts-chartjs.html">Chart JS</a>
                        </li>
                        <li><i class="menu-icon fa fa-area-chart"></i><a href="charts-flot.html">Flot Chart</a></li>
                        <li><i class="menu-icon fa fa-pie-chart"></i><a href="charts-peity.html">Peity Chart</a>
                        </li>
                    </ul>
                </li>

                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false"> <i class="menu-icon fa fa-area-chart"></i>Maps</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="menu-icon fa fa-map-o"></i><a href="maps-gmap.html">Google Maps</a></li>
                        <li><i class="menu-icon fa fa-street-view"></i><a href="maps-vector.html">Vector Maps</a>
                        </li>
                    </ul>
                </li>
                <li class="menu-title">Extras</li><!-- /.menu-title -->
                <!-- <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false"> <i class="menu-icon fa fa-glass"></i>Pages</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="menu-icon fa fa-sign-in"></i><a href="page-login.html">Login</a></li>
                        <li><i class="menu-icon fa fa-sign-in"></i><a href="page-register.html">Register</a></li>
                        <li><i class="menu-icon fa fa-paper-plane"></i><a href="pages-forget.html">Forget Pass</a>
                        </li>
                    </ul>
                </li> -->
                {% endwith %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </nav>
</aside>
{% endif %}

templates/register.html
{% load static %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Ela Admin - HTML5 Admin Template</title>
    <meta name="description" content="Ela Admin - HTML5 Admin Template">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="https://i.imgur.com/QRAUqs9.png">
    <link rel="shortcut icon" href="https://i.imgur.com/QRAUqs9.png">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/normalize.css@8.0.0/normalize.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.0/css/flag-icon.min.css">
    <link rel="stylesheet" href="{% static 'css/cs-skin-elastic.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>

    <!-- <script type="text/javascript" src="https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js"></script> -->
</head>
<body class="bg-dark">

    <div class="sufee-login d-flex align-content-center flex-wrap">
        <div class="container">
            <div class="login-content">
                <div class="login-logo">
                    <a href="index.html">
                        <img class="align-content" src="{% static 'images/logo.png' %}" alt="">
                    </a>
                </div>
                <div class="login-form">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <label>User Name</label>
                            {{form.username}}
                        </div>
                        <div class="form-group">
                            <label>Password</label>
                            {{form.password}}
                        </div>
                        <div class="form-group">
                            <label>NPK</label>
                            {{form.nik}}
                        </div>
                        <div class="form-group">
                            <label>Nama</label>
                            {{form.name}}
                        </div>
                        
                        <button type="submit" class="btn btn-primary btn-flat m-b-30 m-t-30">Register</button>
                        <div class="social-login-content">
                            <div class="social-button">
                                <button type="button" class="btn social facebook btn-flat btn-addon mb-3"><i class="ti-facebook"></i>Register with facebook</button>
                                <button type="button" class="btn social twitter btn-flat btn-addon mt-2"><i class="ti-twitter"></i>Register with twitter</button>
                            </div>
                        </div>
                        <div class="register-link m-t-15 text-center">
                            <p>Already have account ? <a href="{% url 'login' %}"> Sign in</a></p>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.4/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-match-height@0.7.2/dist/jquery.matchHeight.min.js"></script>
    <script src="{% static 'js/main.js' %}"></script>

</body>
</html>